### PR TITLE
feat: Add support for converting from Ansi256 to 16 color.

### PR DESCRIPTION
**Pull request by jwalton**
I'm working on porting Chalk to go, and I noticed that from 4.x to 5.x, this library lost the ability to convert from ANSI 256 color to ANSI 16 color.  Since I need this in my go port, I figured I'd add it back in the JS version too.  ;)

Originally I started looking into how `color-convert` converts these values, but then I realized there's only 256 of them, so it's pretty easy to generate a LUT to convert.  Essentially:

```js
console.log("const ansi256To16 = [");
for (let i = 0; i < 256; i++) {
  const result = colorConvert.ansi256.ansi16(i);
  console.log(`    ${result}`,);
}
console.log("\n];\n");
```

(This also let me find [this issue](https://github.com/Qix-/color-convert/issues/89) in color-convert, so I manually edited this table slightly to fix this.)

So this adds:

* `style.ansi256ToAnsi(code number): number` - converts an ANSI 256 color to a basic ANSI color code.
* `style.color.ansi(code number): string` and `style.bgColor.ansi(code number): string` take a color code (e.g. 30 for black), and returns the appropriate code, similar to `style.color.ansi256` but for 16 color values.

I'm not 100% sold on the names of these functions.  Originally I called it `ansi256ToAnsi16()`, but I feel like that is too close to the existing `ansi256ToAnsi16m()` - would be a bit of a disastrous one-character typo.  Maybe `ansi256ToAnsiBasic()`?
Suggestions welcome.

On iTerm2 on my machine, the output of this looks like:

image

(There's probably some further refinements that could be made to the LUT table - I think some of the colors color-convert generates are wrong.)

### CODE REVIEW

**Comment by jwalton** [comment]
Another alternative here would be to have `style.ansi256ToAnsi()` return the ansi code (e.g. instead of 0 for black, return 30).  Then `style.color.ansi()` would take a code instead of a 0-15.  There's pros and cons either way, I feel, but if someone feels strongly this should be changed, I'm happy to change it.

**Comment by jwalton** [comment]
The more I look at this LUT I generated with color-convert, the less I like it...  I'm going to try to generate one using a least-color-distance algorithm, and see how that turns out (the only downside to this is, I'll have to pick a set of colors as "authentic" and there are lots of [authentic color pallets](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) to pick from).

**Comment by Richienb** [comment]
> Since I need this in my go port, I figured I'd add it back in the JS version too. ;)

Chalk will also drop 16-bit color which is why it was removed here.

**Comment by jwalton** [comment]
> Chalk will also drop 16-bit color which is why it was removed here.

By 16-bit color, you mean 256 color (8-bit color)?  This library still supports converting [from 16.7m color to 256 color](https://github.com/chalk/ansi-styles/blob/main/index.js#L104-L123).  Or do you mean chalk will drop support for standard 16 color ANSI codes?

**Comment by Qix-** [comment]
@jwalton There is no LUT for ansi256 - go check out the code in color-convert; the values are encoded from domain transformations, not arbitrary lookups.

**Comment by jwalton** [comment]
> There is no LUT for ansi256 - go check out the code in color-convert; the values are encoded from domain transformations, not arbitrary lookups

@Qix-  Sorry if I wasn't clear.   I didn't mean to imply there was a LUT in color-convert.

This PR adds a LUT to do the conversion in ansi-styles - I pre-calculated an ANSI16 code for each of the possible ANSI256 codes, and I generate the LUT *using* color-convert.  I know there was a desire to [remove color-convert](https://github.com/chalk/chalk/issues/300) from chalk, so I didn't want to pull color-convert in to do this simple conversion.  Using a LUT for the conversion should also (obviously) be a lot faster than calling into color-convert, since it's just a lookup in an array.

The code I used to generate the LUT was just:

```js
const defaultLut = Array(256)
  .fill()
  .map((_, index) => colorConvert.ansi256.ansi16(index));
```

But, when I try this, the LUT I get has obvious errors in it:

image

You'll notice the top row of colors all map to `30 - black`.  The bottom half of the greyscales all map to black as well.  No color in this whole LUT maps to `90 - bright black`, which is a little weird.  I raised [this issue](https://github.com/Qix-/color-convert/issues/89) in color-convert about this.

(You can print this table yourself with:

```js
function printLut(LUT) {
  console.log("\n\n\nStandard colors");
  for (let i = 0; i < 16; i++) {
    printPair(style.bgColor.ansi256(i), i, LUT[i]);
  }

  console.log("\n\nColors");
  for (let i = 16; i < 232; i++) {
    printPair(style.bgColor.ansi256(i), i, LUT[i]);
    if ((i - 15) % 18 === 0) {
      process.stdout.write("\n");
    }
  }

  console.log("\n\nGreyscale");
  for (let i = 232; i < 256; i++) {
    printPair(style.bgColor.ansi256(i), i, LUT[i]);
    if ((i - 231) % 12 === 0) {
      process.stdout.write("\n");
    }
  }
  console.log("\n\n\n");
}
```
)

So, I just added a new commit to this PR which regenerates the LUT using a closest-distance algorithm:

```js
colorConvert = require("color-convert");

const ANSI_CODES_WINDOWS = [
  { code: 30, color: [0, 0, 0] },
  { code: 31, color: [128, 0, 0] },
  { code: 32, color: [0, 128, 0] },
  { code: 33, color: [128, 128, 0] },
  { code: 34, color: [0, 0, 128] },
  { code: 35, color: [128, 0, 128] },
  { code: 36, color: [0, 128, 128] },
  { code: 37, color: [192, 192, 192] },
  { code: 90, color: [128, 128, 128] },
  { code: 91, color: [255, 0, 0] },
  { code: 92, color: [0, 255, 0] },
  { code: 93, color: [255, 255, 0] },
  { code: 94, color: [0, 0, 255] },
  { code: 95, color: [255, 0, 255] },
  { code: 96, color: [0, 255, 255] },
  { code: 97, color: [255, 255, 255] },
];

const ANSI_CODES_ITERM2 = [
    { code: 30, color: [0, 0, 0] },
    { code: 31, color: [201, 27, 0] },
    { code: 32, color: [0, 194, 0] },
    { code: 33, color: [199, 196, 0] },
    { code: 34, color: [2, 37, 199] },
    { code: 35, color: [201, 48, 199] },
    { code: 36, color: [0, 197, 199] },
    { code: 37, color: [199, 199, 199] },
    { code: 90, color: [103, 103, 103] },
    { code: 91, color: [255, 109, 103] },
    { code: 92, color: [95, 249, 103] },
    { code: 93, color: [254, 251, 103] },
    { code: 94, color: [104, 113, 255] },
    { code: 95, color: [255, 118, 255] },
    { code: 96, color: [95, 253, 255] },
    { code: 97, color: [254, 255, 255] },
  ];

// Computes the square of the distance between too colors.
function colorDistanceSquared(r1, b1, g1, r2, b2, g2) {
  return ((r2 - r1) * (r2 - r1)) + ((b2 - b1) * (b2 - b1)) + ((g2 - g1) * (g2 - g1));
}
function generateAnsi256ToAnsi16LUT(codes = ANSI_CODES_WINDOWS) {
  const LUT = [];

  // First 16 colors in ANSI 256 are exactly the same.
  for (let i = 0; i < 8; i++) {
    LUT[i] = 30 + i;
  }
  for (let i = 8; i < 16; i++) {
    LUT[i] = 90 - 8 + i;
  }

  function findClosestMatch(codes, rgb256) {
    const target = colorConvert.ansi256.rgb(rgb256);

    let minDistance = Infinity;
    let minColor = undefined;
    for (const code of codes) {
      const distance = colorDistanceSquared(
        ...code.color,
        ...target
      );
      // Use <= here because if a given color is equidistant from black and some
      // other color, we want to pick some other color.  Most ANSI is text on a
      // black background, and black on black is hard to read.
      if(distance <= minDistance) {
          minDistance = distance;
          minColor = code.code;
      }
    }

    return minColor
  }

  // For the remaining colors, find the closest match
  for (i = 16; i < 232; i++) {
    LUT[i] = findClosestMatch(codes, i);
  }

  // Same as above, but here we want to restrict ourselves to the greyscales.
  const greys = codes.filter(code => [30,37,90,97].includes(code.code));
  for (let i = 232; i < 256; i++) {
    LUT[i] = findClosestMatch(greys, i);
  }

  return LUT;
}
```

(I'm using color-convert here, but only because it was a handy way to lookup the RGB for each ANSI256 code).  Using `ANSI_CODES_WINDOWS` (the default ANSI codes in Windows 10 CMD.EXE and PowerShell), gives us this LUT:

image

(Note that I'm using windows color codes, but displaying this in iTerm2... Although to be honest there's not a HUGE difference between these LUTs if I use the iTerm2 colors - we're going to 16 colors, it's not going to be "pretty" no matter what.)

Notice here the first 16 colors are correct, there are a lot fewer colors that get crushed to black, the greyscales are better (although there aren't many shades of pure white at the very top of the greyscale - this makes sense though, as most terminals use something quite bright for the default white).

I'm happy to submit a PR to color-convert, too - you could let color-convert generate this LUT the first time someone tries to to an ANSI256 => ANSI16 conversion, and then cache it for subsequent calls.  You could theoretically let someone pass in their own map of 16 terminal colors to try to better match their exact terminal.

**Comment by Qix-** [comment]
A LUT is a ton of extra code that isn't necessary. ANSI256 was designed to be an encoded value. A LUT isn't necessary, that's my point.

Copy the code from `color-convert` if need be. However, I'm not so sure this is functionality we want to support here anyway. Explicitly, the v5 release says that if you need this functionality, use `color-convert`.

I'll leave this up to @sindresorhus but I'm :-1: on this. I agree with the prior decision to remove support.

**Comment by sindresorhus** [comment]
Yeah, we intentionally removed support for this.

**Comment by jwalton** [comment]
> Yeah, we intentionally removed support for this.

Because color-convert is "too slow and flexible" - but this isn't slow at all.  Anyways, if you don't want it that's fine, but then you should [update the readme](https://github.com/chalk/ansi-styles/pull/69).

**Pull request closed without merging**
