### PR TITLE
Feature/rawdata able use raw data do something

### PR DESCRIPTION
**Pull request by bluelovers**
```javascript
const ansiStyles = require('../');

build(['yellow', 'bold']);
build(['yellow', 'bold', 'bgBlue']);

function build(_styles)
{
	let open = function ()
	{
		let code = _styles.reduce((a, b) =>
		{
			a.push(ansiStyles[b].data[0]);

			return a;
		}, []).join(';');

		return `\u001B[${code}m`;
	};

	let close = function ()
	{
		let code = _styles.reduce((a, b) =>
		{
			a.push(ansiStyles[b].data[1]);

			return a;
		}, []).join(';');

		return `\u001B[${code}m`;
	};

	_log(open(), _styles.join(' '), close());
}

function _log(...argv)
{
	console.log(...argv);
	console.dir(argv);
}

```

### CODE REVIEW

**Comment by Qix-** [comment]
Not sure what this improves. Why don't `open` and `close` work?

**Comment by bluelovers** [comment]
when use this patch

i can do some like

```javascript
//a_packed_fn: yellow.bold
process.stdout.write(a_packed_fn.code_open)
process.stdout.write('something we wanna show')
console.log('something we wanna show')
process.stdout.write(a_packed_fn.code_close)
```

---easy than use---

```javascript
forEach(_styles)
{
//get color open
}

//do something output
process.stdout.write('something we wanna show')
console.log('something we wanna show')

forEach(_styles)
{
//get color close
}
```

**Comment by bluelovers** [comment]
i write a chalk style console module

without this patch
i need use chalk source coed for make it work

but with this patch
anyone can easy make they module do something with chalk




```javascript
const chalk = require('chalk');
const ansiStyles = require('../');

let aobj = Buffer.from('7777777777777777')

// wanna easy print something fllow console.log with color, but we can't make it same as console.log do!!
console.dir(chalk.yellow.bold(aobj)) // a fail code
console.log(chalk.yellow.bold(aobj)) // a fail code
chalk.yellow.bold(console.log(aobj)) // a fail code

//-------

let color = build(['yellow', 'bold']);

// we can easy color print anything, without write many code for make a new console.log and use some chalk source code
process.stdout.write(color.open())
console.dir(aobj)
console.log(aobj)
process.stdout.write(color.close())

function build(_styles)
{
	let open = function ()
	{
		let code = _styles.reduce((a, b) =>
		{
			a.push(ansiStyles[b].data[0]);

			return a;
		}, []).join(';');

		return `\u001B[${code}m`;
	};

	let close = function ()
	{
		let code = _styles.reduce((a, b) =>
		{
			a.push(ansiStyles[b].data[1]);

			return a;
		}, []).join(';');

		return `\u001B[${code}m`;
	};

	//_log(open(), _styles.join(' '), close());

	return {
		open: open,
		close: close,
	};
}

```

**Comment by bluelovers** [comment]
```javascript
let n1 = ansiStyles['yellow'].open.replace(/\u001B\[([\d;]+)m/, '$1');
console.dir(n1);
```

---vs---

```javascript
let n2 = ansiStyles['yellow'].data[0];
console.dir(n2);
```

**Comment by Qix-** [comment]
Can you replace `data` -> `raw`? :)

---

@sindresorhus thoughts on this? Seems harmless enough.

**Comment by bluelovers** [comment]
@Qix- done

**Comment by sindresorhus** [comment]
Needs a test and to be documented in the readme. This pull request also needs a better title.

**Comment by sindresorhus** [comment]
@Qix- I didn't realize you could have multiple styles in one escape code. Is this something we should take advantage of it Chalk?

**Comment by bluelovers** [comment]
@sindresorhus  I am not good with words
can u tell me what title i should use

---

this change not only for make it pack as one code,
it just a  example for what can do

just make ppl can do more with ansi-styles, chalk

**Comment by Qix-** [comment]
@sindresorhus we could but there's little functional difference. If be interested if there was a performance increase.

**Comment by bluelovers** [comment]
hope can add this patch or something like this

**Comment by sindresorhus** [comment]
@bluelovers This is not going to get merged without a test and docs. I don't have time to finish this for you. Maybe @Qix- does.

**Comment by Qix-** [comment]
Closing this in lieu of some of the improvements @sindresorhus and I have been discussing.

**Pull request closed without merging**
