### PR TITLE
Inline union of CSS colors for TypeScript type

### LINKED ISSUE #58: Why is @types/color-name a production dependency?
Just curious. We are using ansi-styles via chalk, and I saw this in upstream dependencies and wondered why a types file was in prod deps!

Thanks!

cc @allenhsieh

### PR DESCRIPTION
**Pull request by Richienb**
Fixes #58 

// @sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
Put the elements of separate lines with the line starting with the pipe character.

**Comment by Richienb** [comment]
@sindresorhus Done!

**Comment by Qix-** [comment]
Meh, this seems needless. It's a tiny dependency. The code is going to be here anyway - we're just shifting it around, with the added negative that if the upstream dependency updates, we'll be out of sync.

This isn't solving any problems, aside from placating the woes of those who have not had to maintain the divergence of Typescript and Javascript over the last 5+ years...

**Comment by Richienb** [comment]
> upstream dependency updates

Do you mean the CSS spec?

IMO, we should be keeping the dependency in here but I'm not making the choices.

**Comment by Qix-** [comment]
> Do you mean the CSS spec?

That's the obvious case, but any small errors in the type definitions (since we do not maintain them) or any changes in the typescript itself to better help typescript users, etc. Could be a number of things.

This change exists because someone is asking for a few less HTTP requests during `npm i`. It's not reducing code size by much since all of the color names are being copied over anyway.

It's bikeshedding but it's just.. not the right solution.

**Comment by sindresorhus** [comment]
@Qix- I said yes to this as the CSS colors are very unlikely to change. Also, the dependency we're using is maintained by DefinitelyTyped, not the `color-name` maintainer, and it is not automatically kept in sync. So there's not much benefit of depending on this dependency.

**Pull request merged**
